# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Disable Graphics
      run: |
        sudo lspci -tvvv
        sudo bash -c "echo 1 > /sys/devices/pci0000:00/0000:00:08.0/remove"
        sudo bash -c "echo 1 > /sys/devices/pci0000:00/0000:00:07.3/remove"
        sudo bash -c "echo 1 > /sys/devices/pci0000:00/0000:00:07.1/remove"
        sudo bash -c "echo 1 > /sys/devices/pci0000:00/0000:00:07.0/remove"
        sudo bash -c "echo 1 > /sys/devices/pci0000:00/0000:00:00.0/remove"
        sudo lspci -tvvv
    - name: Build
      run: docker build .
